name: CPU Validation

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'cpu/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'cpu/**'

jobs:
  build:
  
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        working-directory: cpu/

    steps:
    - uses: actions/checkout@v4
    - name: Install Icarus Verilog and Verilator
      run: sudo apt-get install -y iverilog verilator
    - name: Build
      run: ./scripts/build_all.sh
    - name: Run tests
      run: ./build/iverilog/Vtest && ./build/verilator/Vtest
